name: Test Publish to NPM

on:
  create:
    tags:
      - '**'

permissions:
  contents: read

jobs:
  release:
    if: github.repository == 'toridoriv/cheerio'
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - name: Build project
        run: npm run build && npm pack .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ./toridoriv-cheerio-${{ steps.version.outputs.value }}.tgz
          name: toridoriv-cheerio-${{ steps.version.outputs.value }}.tgz
