name: Test Publish to NPM

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    if: github.repository == 'toridoriv/cheerio'
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "This is a test for publishing to NPM"